export const DemoStudents = [
    ['Danielle', 'Conrad', 'ADM07LXL4KQ', 'montes@quam.net', 1959],
    ['Sharon', 'Melendez', 'SYD06OCU6PI', 'laoreet.posuere.enim@eu.ca', 3380],
    ['Stephen', 'Colon', 'JZJ20BPR7XH', 'metus@natoquepenatibuset.edu', 1610],
    [
        'Keith',
        'Mcfadden',
        'BGP09LTZ5YO',
        'ultricies.sem.magna@aliquameros.org',
        3954,
    ],
    ['Preston', 'Rice', 'QFE47GNG8HU', 'ut@nec.net', 7481],
    ['Barbara', 'Mcintosh', 'CJL27XOJ7RE', 'ac@tortor.net', 1621],
    ['Jerry', 'Hodges', 'SBZ18QGZ2UL', 'elementum@lobortisnisi.edu', 5004],
    ['Matthew', 'Benjamin', 'QHU71WMR7MX', 'dictum.augue@Aenean.edu', 8235],
    [
        'Elizabeth',
        'Henderson',
        'LBH41PRU7RH',
        'nibh.dolor.nonummy@iaculisquis.ca',
        3595,
    ],
    ['Nelle', 'Leon', 'YYH62JYW5RO', 'mattis@dolor.edu', 3692],
    ['Camden', 'Gray', 'NVX45GKN8ZH', 'magna.Cras@aliquet.org', 2054],
    ['Lois', 'Whitaker', 'FHO34UDC3HD', 'ornare.lectus.justo@ut.ca', 9350],
    ['Jillian', 'Anthony', 'PAV63UHH8QL', 'eu@velarcu.org', 3504],
    ['Brenna', 'Sheppard', 'GGN28NMW2AZ', 'Aliquam.vulputate@lectus.edu', 6344],
    [
        'Quincy',
        'Hewitt',
        'TXC88RDE0RB',
        'Duis.elementum@ipsumdolorsit.co.uk',
        2425,
    ],
    ['Tashya', 'Burris', 'NMW00OGU0EF', 'sagittis@uteratSed.ca', 9046],
    [
        'Aileen',
        'Deleon',
        'LLD98TQH8VY',
        'feugiat.Lorem.ipsum@nisiAenean.ca',
        2150,
    ],
    [
        'Barrett',
        'Riddle',
        'ALR65DDR2WD',
        'mollis.nec.cursus@liberomaurisaliquam.com',
        2160,
    ],
    ['Wing', 'Howell', 'QAQ08XCD4AD', 'dapibus@duiinsodales.net', 5198],
    [
        'Reed',
        'Mcleod',
        'IAN85XKH0JU',
        'lorem.ipsum.sodales@massaVestibulumaccumsan.net',
        7917,
    ],
    ['Hamilton', 'Sharp', 'ZSP43JRD8SD', 'senectus@egestas.net', 1654],
    ['Bernard', 'Pickett', 'FRO22YHE5UT', 'elit.a.feugiat@Nullamenim.edu', 3857],
    ['Porter', 'Heath', 'NQL39FIW3JX', 'mi@inconsectetueripsum.com', 5775],
    ['Keelie', 'Manning', 'EPO73EQX7OP', 'libero.nec.ligula@nonenim.net', 1355],
    ['Erich', 'York', 'ENU87PQN8AQ', 'a.sollicitudin@Morbivehicula.net', 3275],
    ['Armand', 'Lynn', 'SSC33PUT4YT', 'malesuada@sedhendrerita.net', 9831],
    ['Aristotle', 'Lopez', 'GVO21PJY6SU', 'at.lacus@Nulla.org', 6323],
    [
        'Grace',
        'Burnett',
        'CXT87RXF0MP',
        'lacus.Quisque.purus@orcitinciduntadipiscing.org',
        2474,
    ],
    ['Kevin', 'Walton', 'JSL01GMJ6TV', 'Curabitur@mattisCras.ca', 2554],
    ['Ryan', 'Gallagher', 'JTN53GWV5MV', 'leo.Vivamus.nibh@Nullam.edu', 4920],
    ['Marsden', 'Scott', 'FEW87XTQ2ES', 'Nullam.velit.dui@mi.net', 1212],
    ['Jasmine', 'Robbins', 'MQZ27YIU3QT', 'et.magnis.dis@mifringillami.ca', 2393],
    [
        'Nicholas',
        'Foley',
        'JTZ08GNA3GN',
        'Aliquam.gravida.mauris@Nulla.co.uk',
        9825,
    ],
    ['Kyra', 'Santos', 'UNU25RBN4UP', 'non.ante.bibendum@est.org', 4650],
    [
        'Audra',
        'Beck',
        'DTU48QDA5OA',
        'in.lobortis@interdumCurabiturdictum.com',
        5614,
    ],
    ['Rudyard', 'Fowler', 'RTX57HMH6VK', 'nec@Nunclectus.edu', 4728],
    ['Shelby', 'Lambert', 'ZCF02FWU8SD', 'mollis.Duis@sedorcilobortis.com', 3239],
    [
        'Kelsey',
        'Chen',
        'MPD30VFS4WH',
        'orci.Ut.semper@dapibusgravidaAliquam.net',
        5932,
    ],
    ['Claudia', 'Stephenson', 'SMK50XBB5LC', 'Suspendisse@ornareFusce.edu', 6473],
    [
        'Xander',
        'Donaldson',
        'KUA48LMF0NG',
        'arcu.vel@cursuspurusNullam.com',
        2626,
    ],
    ['Brody', 'Ryan', 'VQP67UIW2HM', 'morbi@acnulla.co.uk', 5315],
    [
        'Russell',
        'Nieves',
        'LIH80LTU4DI',
        'arcu.Vestibulum.ante@Morbisitamet.org',
        3643,
    ],
    ['Hamish', 'Jenkins', 'BMH67JLJ0IT', 'ipsum.primis.in@Aeneaneget.edu', 6777],
    ['Gwendolyn', 'Simpson', 'FVH83SNK4LW', 'non@lobortis.edu', 7674],
    ['Mercedes', 'Morton', 'HEO90ARS9WG', 'faucibus.orci@Craslorem.co.uk', 8443],
    ['Ahmed', 'Hanson', 'NGT88TQX5NC', 'sem@rutrumFuscedolor.edu', 2332],
    ['Gemma', 'Newman', 'SLU24FNL6RI', 'Cras.dolor@Etiam.ca', 9530],
    ['Sheila', 'Adkins', 'FUY53NZG9UX', 'amet.consectetuer@estNunc.org', 1827],
    [
        'Hammett',
        'Summers',
        'XKT54EBS7UK',
        'non.dui@Maecenasmalesuadafringilla.net',
        9455,
    ],
    ['Avram', 'Vazquez', 'UGU18NCM9JC', 'mus@arcu.net', 6893],
    [
        'Kaitlin',
        'Drake',
        'EMF86FTL6HJ',
        'enim.sit.amet@volutpatNulladignissim.com',
        9753,
    ],
    ['Lael', 'May', 'AEF45LCW9MP', 'blandit.viverra@amet.co.uk', 8268],
    [
        'Anastasia',
        'Graham',
        'GXN07VKI3ZU',
        'mauris.sit.amet@Vestibulum.co.uk',
        7762,
    ],
    ['Lucas', 'Fuentes', 'ZNF39BVF7CP', 'consectetuer.ipsum.nunc@erat.edu', 3977],
    ['John', 'Stein', 'YPS58ZUM4TL', 'torquent.per@tellusSuspendisse.net', 9265],
    ['Hedy', 'Dodson', 'DXY24FEK6YU', 'diam.at.pretium@a.edu', 6223],
    ['Jerome', 'Bradford', 'JHK32VZT2TS', 'dignissim@gravidanunc.org', 9444],
    [
        'Hayden',
        'Kelly',
        'JCV60CKS6CM',
        'vulputate.risus.a@imperdietullamcorperDuis.org',
        4878,
    ],
    ['Shay', 'Decker', 'FOX36WBZ2SQ', 'cursus@etmagnis.com', 7113],
    ['Kathleen', 'Hurst', 'RUU91JGP1GU', 'Duis.dignissim@ultriciessem.com', 8661],
    ['Alvin', 'David', 'DBV56XES7EK', 'semper.dui@feliseget.edu', 1254],
    ['Orla', 'Noble', 'FZT61ACR7ZS', 'orci@aodiosemper.com', 8847],
    [
        'Cassandra',
        'Landry',
        'CJK43QMG5CN',
        'tincidunt.dui.augue@uteratSed.edu',
        1640,
    ],
    ['Price', 'Small', 'PUT98MOP9YX', 'Phasellus.at@enimSednulla.edu', 3916],
    ['Sage', 'Whitley', 'BDV84JRF9ZM', 'dapibus.rutrum.justo@diam.com', 6151],
    [
        'Fleur',
        'Bradford',
        'RYU95TNI3LV',
        'Etiam.gravida@milaciniamattis.org',
        5559,
    ],
    ['Dylan', 'Lara', 'EQE82DPI5EC', 'viverra.Maecenas@arcu.net', 9615],
    ['Donovan', 'Klein', 'XQE87ALQ7VQ', 'faucibus@dolorNullasemper.edu', 2437],
    ['Elvis', 'Valdez', 'OFX60RNQ4SR', 'laoreet.lectus@Integerid.com', 8340],
    ['Trevor', 'Wilcox', 'WUT07CFD4HL', 'nisi.a.odio@fringilla.co.uk', 8580],
    ['Hop', 'Tanner', 'MQD63NGJ2FL', 'in.magna@nonfeugiat.net', 9438],
    ['Hasad', 'Velazquez', 'FGL72USF5QH', 'sed.dictum@risusNulla.co.uk', 1560],
    ['Victor', 'Lindsay', 'SPS31MFU9UC', 'neque@a.com', 2548],
    ['Lacey', 'Cobb', 'ORP29IDL7XA', 'nec.mauris@eratin.net', 8246],
    [
        'Patience',
        'Moreno',
        'SWD33CQH4SY',
        'ligula.Aenean.euismod@loremipsumsodales.org',
        1987,
    ],
    ['Kyle', 'Matthews', 'WQW45YDS9RY', 'Donec@Aliquam.com', 2446],
    [
        'Driscoll',
        'Kent',
        'LLG14HRH9YG',
        'sit.amet.dapibus@Proinvelnisl.edu',
        2040,
    ],
    ['Jamal', 'Henderson', 'DGV50PDP6CD', 'sem@fermentumconvallis.org', 9677],
    [
        'Felix',
        'Whitaker',
        'SVR22AYC9IN',
        'auctor.vitae.aliquet@sapienCras.ca',
        4616,
    ],
    [
        'Jermaine',
        'Brewer',
        'OKL88OHU1PY',
        'dictum.Phasellus@aliquetnec.co.uk',
        1598,
    ],
    ['Jena', 'Goodman', 'WVD52BBJ0TF', 'auctor@arcuNuncmauris.net', 6603],
    ['Alexandra', 'Ryan', 'PQU94OYA0XC', 'arcu.imperdiet@sedpede.edu', 9672],
    [
        'Eugenia',
        'Cherry',
        'KOP99NJJ9YM',
        'primis.in.faucibus@consequatnec.co.uk',
        2016,
    ],
    [
        'Walker',
        'Pittman',
        'GZL06EGY6VG',
        'tristique.pharetra@Sedidrisus.edu',
        1560,
    ],
    ['Lois', 'Mays', 'ECX37MPR1YY', 'Proin.velit.Sed@vitaeerat.com', 1153],
    ['Angela', 'Vaughan', 'UOQ16TVK7JV', 'interdum.libero@et.org', 4085],
    ['Wade', 'Hardy', 'RZJ10NKO3ES', 'In.nec@Uttincidunt.ca', 9579],
    [
        'Armando',
        'Duncan',
        'HMK78VFR2ZQ',
        'eros.nec.tellus@anteVivamus.co.uk',
        8867,
    ],
    ['Odette', 'Kramer', 'NAA45LZM5BZ', 'elit.pede@necleoMorbi.net', 2405],
    ['Kuame', 'Moody', 'MNT40MYY3SC', 'magna@ultriciesligula.net', 5554],
    ['Charity', 'Hinton', 'CLR44DOU2NV', 'sit@natoque.co.uk', 9463],
    ['Aileen', 'Frazier', 'CEK41UMO7TS', 'Mauris@utnisi.ca', 8962],
    [
        'Kellie',
        'Holder',
        'SGP53MQM5GW',
        'mi.felis.adipiscing@lobortisquama.edu',
        2084,
    ],
    ['Lawrence', 'Fry', 'JSP76NKR2MT', 'mus@Vestibulumaccumsanneque.ca', 9215],
    ['Hammett', 'Humphrey', 'IIT26PXK7VJ', 'Pellentesque@nuncIn.ca', 1585],
    [
        'Gary',
        'Newton',
        'VPI84TYZ9QA',
        'lorem.semper.auctor@vehiculaetrutrum.edu',
        6793,
    ],
    [
        'Yardley',
        'Heath',
        'ASR06IJI1UT',
        'sodales.Mauris@DonectinciduntDonec.com',
        2016,
    ],
    ['Charde', 'Church', 'WVM79YAK7GO', 'eget@malesuadaIntegerid.edu', 4856],
    ['Isabelle', 'Blake', 'YWT19KAJ8YR', 'Nam.porttitor@ridiculus.net', 1853],
    [
        'Renee',
        'Garrett',
        'OGO90FCA9AY',
        'vulputate.posuere@ametconsectetueradipiscing.net',
        1330,
    ],
];

export const DemoTeachers = [
    ['Orlando', 'Hewitt', 'malesuada.malesuada@veliteusem.org'],
    ['Taylor', 'Larson', 'interdum.Nunc.sollicitudin@justo.org'],
    ['Yvette', 'Hogan', 'velit.Sed.malesuada@diamProindolor.ca'],
    ['Galvin', 'Flowers', 'Sed.diam.lorem@loremegetmollis.com'],
    ['Sylvester', 'Mejia', 'sit@arcuVestibulumut.ca'],
    ['Burke', 'Carver', 'Pellentesque.habitant.morbi@Nuncsed.org'],
    ['Eaton', 'Mathews', 'a.nunc@tempor.ca'],
    ['Brian', 'Spencer', 'arcu.Vestibulum@Nullam.edu'],
    ['Micah', 'Mathis', 'aliquet.libero.Integer@mattisIntegereu.net'],
    ['Addison', 'Wiley', 'tortor.Integer@erosnec.org'],
    ['Linda', 'Preston', 'mus.Aenean@diamDuis.com'],
    ['Owen', 'Stein', 'orci.Ut@eu.ca'],
    ['Brock', 'Ortega', 'at.augue.id@parturient.com'],
    ['Maia', 'Chang', 'varius.Nam.porttitor@nonhendreritid.co.uk'],
    ['Rhonda', 'Clemons', 'ullamcorper.eu@lectusquismassa.com'],
    ['Karly', 'Dudley', 'Phasellus@vel.org'],
    ['Amery', 'Burns', 'Donec.fringilla.Donec@quis.co.uk'],
    ['Nadine', 'Floyd', 'justo@tinciduntadipiscingMauris.org'],
    ['Roth', 'Daniels', 'ornare@scelerisqueneque.co.uk'],
    ['Isaac', 'Cox', 'eu.placerat@interdumCurabitur.edu'],
    ['Connor', 'Shannon', 'egestas.blandit@nislarcuiaculis.ca'],
    ['Kyle', 'Roth', 'Vestibulum.ut@tincidunt.co.uk'],
    ['Grady', 'Cantu', 'augue@ipsumac.net'],
    ['Nell', 'Nunez', 'fringilla@Curabiturdictum.com'],
    ['Kessie', 'Massey', 'volutpat.nunc.sit@ametluctusvulputate.ca'],
    ['Samantha', 'Blankenship', 'ac.nulla@seddictumeleifend.edu'],
    ['Emily', 'Patton', 'consectetuer.ipsum.nunc@Donectempor.co.uk'],
    ['Gannon', 'Macias', 'vulputate.posuere.vulputate@maurisblanditmattis.net'],
    ['Clinton', 'Nash', 'hendrerit@pretiumet.com'],
    ['Karyn', 'Dyer', 'nec.enim@id.net'],
    ['Eagan', 'Mckenzie', 'non.vestibulum@fermentumarcu.com'],
    ['Kimberley', 'Mcpherson', 'diam.vel@pharetra.ca'],
    ['Galena', 'Hurst', 'nunc@semper.edu'],
    ['Leigh', 'Franco', 'Duis.a.mi@Aeneansedpede.co.uk'],
    ['Guy', 'Blake', 'malesuada.fringilla@massalobortisultrices.edu'],
    ['Alea', 'Mendoza', 'enim@noncursusnon.co.uk'],
    ['Xena', 'Ingram', 'a@tristique.edu'],
    ['Howard', 'Stein', 'id.enim.Curabitur@nascetur.co.uk'],
    ['Justin', 'Hancock', 'pede.Nunc.sed@augueut.edu'],
    ['Irma', 'Payne', 'pretium@mauris.com'],
    ['Doris', 'Calhoun', 'mollis@ullamcorperviverra.co.uk'],
    ['Lani', 'Poole', 'malesuada.Integer@Suspendisse.ca'],
    ['Garth', 'Sutton', 'fringilla.euismod@Cumsociis.ca'],
    ['Uma', 'Erickson', 'In.nec.orci@QuisquevariusNam.ca'],
    ['Bethany', 'Collier', 'at@idrisusquis.net'],
    ['Charles', 'Sanford', 'suscipit@tincidunt.net'],
];

export const DemoCourses = [
    [15, 'risus, at fringilla purus mauris', 53, 4],
    [31, 'ac', 51, 1],
    [31, 'adipiscing elit. Curabitur', 87, 3],
    [31, 'facilisis.', 97, 7],
    [39, 'diam. Sed diam lorem, auctor', 95, 7],
    [24, 'sed turpis nec', 79, 8],
    [23, 'et,', 64, 8],
    [20, 'augue scelerisque mollis.', 84, 8],
    [30, 'imperdiet nec, leo. Morbi', 96, 6],
    [16, 'in', 90, 7],
    [33, 'purus, in', 92, 6],
    [38, 'Mauris eu turpis.', 54, 4],
    [25, 'In nec', 75, 2],
    [9, 'dui', 71, 4],
    [26, 'hendrerit. Donec porttitor tellus', 51, 7],
    [10, 'auctor ullamcorper, nisl', 75, 1],
    [27, 'in, cursus et,', 61, 4],
    [19, 'quam. Curabitur vel lectus.', 96, 8],
    [6, 'amet ornare lectus justo', 95, 8],
    [8, 'egestas a, dui. Cras pellentesque.', 91, 7],
    [26, 'Donec feugiat metus', 77, 2],
    [12, 'augue scelerisque mollis. Phasellus libero', 68, 6],
    [26, 'massa non ante', 54, 2],
    [9, 'Aliquam gravida mauris', 63, 6],
    [17, 'dolor. Donec fringilla. Donec', 52, 8],
    [30, 'malesuada vel, convallis in,', 73, 4],
    [25, 'in sodales elit erat', 60, 5],
    [21, 'tempus risus. Donec egestas. Duis', 98, 3],
    [3, 'vitae, sodales', 63, 2],
    [37, 'eu sem.', 52, 4],
    [13, 'id', 78, 1],
    [29, 'Nullam enim. Sed', 67, 4],
    [37, 'euismod', 55, 7],
    [13, 'sem, vitae aliquam eros turpis', 82, 6],
    [36, 'Donec sollicitudin adipiscing ligula. Aenean', 86, 3],
    [18, 'euismod in, dolor. Fusce feugiat.', 76, 4],
    [10, 'dictum placerat,', 76, 5],
    [29, 'Cum sociis natoque penatibus', 51, 3],
    [11, 'est ac', 70, 1],
    [7, 'sit amet,', 89, 2],
    [38, 'malesuada vel,', 55, 6],
    [15, 'lacinia', 94, 8],
    [33, 'nec', 75, 5],
    [11, 'in aliquet lobortis,', 56, 2],
    [32, 'dapibus gravida. Aliquam', 54, 4],
    [14, 'tempor arcu. Vestibulum', 54, 6],
    [28, 'semper auctor.', 74, 2],
    [1, 'cursus vestibulum.', 81, 7],
    [10, 'nulla.', 63, 2],
    [21, 'gravida molestie arcu. Sed eu', 86, 5],
    [36, 'bibendum sed, est. Nunc', 88, 4],
    [23, 'ultrices', 66, 2],
    [10, 'orci', 90, 3],
    [8, 'consequat, lectus sit', 91, 4],
    [23, 'orci', 71, 7],
    [28, 'eleifend egestas. Sed pharetra, felis', 57, 8],
    [24, 'a, arcu. Sed et libero.', 72, 2],
    [18, 'est arcu ac orci.', 58, 5],
    [23, 'mollis non, cursus non, egestas', 64, 4],
    [20, 'scelerisque, lorem ipsum sodales', 75, 4],
    [2, 'arcu.', 57, 4],
    [19, 'erat neque non quam.', 87, 3],
    [35, 'Suspendisse sed', 94, 5],
    [22, 'a,', 94, 5],
    [30, 'tristique aliquet. Phasellus fermentum convallis', 84, 7],
    [39, 'faucibus', 91, 6],
    [12, 'enim, gravida sit amet,', 52, 4],
    [26, 'aliquet odio. Etiam', 61, 8],
    [28, 'mauris eu elit. Nulla', 80, 7],
    [20, 'odio,', 53, 5],
    [5, 'ut odio vel est', 86, 6],
    [26, 'Sed', 59, 6],
    [25, 'augue scelerisque mollis. Phasellus libero', 77, 5],
    [4, 'lorem tristique', 93, 3],
    [14, 'vel,', 88, 7],
    [31, 'a felis ullamcorper', 99, 5],
    [38, 'Vestibulum', 90, 7],
    [8, 'amet, risus. Donec nibh', 97, 6],
    [5, 'volutpat nunc sit amet metus.', 92, 6],
    [17, 'ultricies sem magna', 70, 4],
    [3, 'blandit viverra. Donec tempus, lorem', 56, 2],
    [14, 'mauris. Integer', 90, 1],
    [25, 'sodales nisi magna sed', 80, 1],
    [9, 'lacus.', 54, 3],
    [8, 'natoque', 50, 1],
    [22, 'a, malesuada', 69, 5],
    [37, 'in sodales elit', 51, 5],
    [14, 'Cras vulputate velit eu', 56, 2],
    [37, 'egestas, urna', 93, 2],
    [3, 'eros. Nam consequat dolor', 73, 7],
    [36, 'vulputate,', 90, 7],
    [11, 'a,', 82, 2],
    [26, 'dui nec urna suscipit', 61, 1],
    [2, 'dictum ultricies ligula. Nullam', 92, 3],
    [22, 'rutrum', 65, 4],
    [35, 'ligula. Aenean', 89, 6],
    [32, 'ipsum. Suspendisse sagittis. Nullam vitae', 85, 6],
    [5, 'sit amet', 51, 5],
    [7, 'Fusce mollis. Duis sit', 78, 8],
    [10, 'mattis ornare,', 52, 5],
];
